default_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from default_django_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('responsive-form/', include('responsive_form.urls')),
    path('image_handler/', include('image_handler.urls')),
    path('features/', include('features.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

features/urls.py
from django.urls import path, include

from features import views


app_name = 'features'
urlpatterns = [
    path('multipleselect/', views.MultipleSelect, name='multiple_select'),
    path('multiple_divison/', views.MultipleDivison, name='multiple_divison'),
]

image_handler/image_crop/urls.py
from django.urls import path

from image_handler.image_crop import views

urlpatterns = [
    path('create/', views.photo_list, name='image_crop'),
]

image_handler/image_drag_and_drop/urls.py
from django.urls import path

from image_handler.image_drag_and_drop import views

urlpatterns = [
    path('', views.DragAndDropImage, name='image_drag_and_drop'),
    path('upload/', views.dropzoneuploads, name='upload_images'),
]

image_handler/urls.py
from django.urls import path, include

from image_handler import views


app_name = 'image_handler'
urlpatterns = [
    path('image_crop/', include('image_handler.image_crop.urls')),
    path('image_drag_and_drop/', include('image_handler.image_drag_and_drop.urls')),
]

responsive_form/urls.py
from django.urls import path, include

from responsive_form import views

app_name = 'responsive_from'
urlpatterns = [
    path('create/', views.CreateForm, name='create_from'),
]

features/models.py
from django.db import models

# Create your models here.

image_handler/image_crop/models.py
from django.db import models

class Photo(models.Model):
    file = models.ImageField()
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

image_handler/models.py
from django.db import models

# Create your models here.

image_handler/image_crop/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo


class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    # file = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn-info'}))
    # file = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn-info'}), label='Select Image ',
    #                        help_text='Help text is written here')

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height',)

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

default_django_project/views.py
from django.shortcuts import render


def Dashboard(request):
    return render(request, 'dashboard/dashboard.html')

features/views.py
from django.shortcuts import render


def MultipleSelect(request):
    data_breadcrumb = {
        'name': 'Multiple Select',
        'active': 'active'
    }

    context = {
        'data_breadcrumb': data_breadcrumb
    }
    return render(request, 'features/multiple_select/multipleselect.html', context)


def MultipleDivison(request):
    data_breadcrumb = {
        'name': 'Multiple Division',
        'active': 'active'
    }

    context = {
        'data_breadcrumb': data_breadcrumb
    }
    return render(request, 'features/multiple_division/multipledivison.html', context)

image_handler/image_crop/views.py
from django.shortcuts import render, redirect

from .models import Photo
from .forms import PhotoForm


def photo_list(request):
    photos = Photo.objects.all()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('image_handler:image_crop')
    else:
        form = PhotoForm()

    data_breadcrumb = {
        'name': 'Crop Image',
        'active': 'active'
    }

    context = {
        'form': form,
        'photos': photos,
        'data_breadcrumb': data_breadcrumb
    }

    return render(request, 'image_crop/image_crop.html', context)

image_handler/image_drag_and_drop/views.py
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.shortcuts import render


def DragAndDropImage(request):
    data_breadcrumb = {
        'name': 'Drag and Drop image',
        'active': 'active'
    }
    context = {
        'data_breadcrumb': data_breadcrumb
    }
    return render(request, 'image_drag_and_drop/image_drag_and_drop.html', context)


def dropzoneuploads(request):
    if request.method == 'POST':
        files = [request.FILES.get('file[%d]' % i)
                 for i in range(0, len(request.FILES))]
        # inputs obtained from form are grabbed here, similarly other data can be gathered
        abc = request.POST['abc']
        # location where you want to upload your files
        folder = 'my_folder'
        fs = FileSystemStorage(location=folder)
        for f in files:
            filename = fs.save(f.name, f)
    data = {'status': 'success'}
    response = JsonResponse(data)
    return response

image_handler/views.py
from django.shortcuts import render

# Create your views here.

responsive_form/views.py
from django.shortcuts import render


def CreateForm(request):
    return render(request, 'form_temp/create.html')

default_django_project/templates/default_django_project/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Django Dashboard</title>
    {% block responsive %}
        {% include 'base_site/base_css.html' %}
    {% endblock %}
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}
</head>
<body class="primary-background">
<div class="secondary-background"></div>
{% block header %}
    {% include 'base_site/header.html' %}
{% endblock %}
<div class="wrapper">
    {% block side_navigation %}
    {% endblock %}
    <div id="content">
        <div class="container-fluid">
            {% block breadcrumbs %}
{#                {% include 'base_site/breadcrumbs.html' %}#}
            {% endblock %}

            {% block messages %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% block footer %}
{% endblock %}
{% block headerjs %}
        {% include 'base_site/base_js.html' %}
{% endblock %}
{% block js %}
{% endblock %}

</body>
</html>

features/templates/features/multiple_division/multipledivison.html
{% extends 'default_django_project/base.html' %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'features/css/multiple_divison/multiple_divison.css' %}">
{% endblock %}

{% block side_navigation %}
    {% include 'base_site/side_navigation.html' %}
{% endblock %}
{% block breadcrumbs %}
    {% include 'base_site/breadcrumbs.html' with data=data_breadcrumb %}
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h6>Feature Multiple Divison</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {#                            <div>#}
                            {#                                <div class="input_fields_container">#}
                            {#                                    <div><input type="text" name="product_name[]">#}
                            {#                                        <button class="btn btn-sm btn-primary add_more_button">Add More Fields</button>#}
                            {#                                    </div>#}
                            {#                                </div>#}
                            {#                            </div>#}
                            <br>
                            <div>
                                <h6>Dynamic Add / Remove</h6>
                                <div class="multi-field-wrapper">
                                    <div class="multi-fields">
                                        <div class="multi-field">
                                            <div class="remove-btn">
                                                <button type="button" class="remove-field btn"><i
                                                        class="fa fa-times"></i>
                                                </button>
                                            </div>
                                            <br>
                                            <div>
                                                <div class="form-group">
                                                    <label>Label:</label>
                                                    <input class="form-control" type="text" required>
                                                    <small class="form-text text-muted">Help text written here</small>
                                                </div>
                                                <div class="form-group">
                                                    <label>Label:</label>
                                                    <input class="form-control" type="text" required>
                                                    <small class="form-text text-muted">Help text written here</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <button type="button"
                                                class="add-field custom-button btn btn-primary"><i
                                                class="fa fa-plus">&nbsp; Add More</i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript"
            src="{% static 'features/js/multiple_divison/multiple_divison.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'features/js/multiple_divison/multiple-field-wrapper.js' %}"></script>
{% endblock %}

features/templates/features/multiple_select/multipleselect.html
{% extends 'default_django_project/base.html' %}
{% load static %}
{% block side_navigation %}
    {% include 'base_site/side_navigation.html' %}
{% endblock %}
{% block breadcrumbs %}
    {% include 'base_site/breadcrumbs.html' with data=data_breadcrumb %}
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h6>Feature Multiple Select</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="form-check form-check">
                                    <input class="form-check-input" type="checkbox" id="selectall">
                                    <label class="form-check-label" for="Checkbox1">Select All</label>
                                </div>
                                <br>
                                <div class="form-check form-check">
                                    <input class="form-check-input" type="checkbox" id="Checkbox1">
                                    <label class="form-check-label" for="Checkbox1">Option 1</label>
                                </div>
                                <div class="form-check form-check">
                                    <input class="form-check-input" type="checkbox" id="Checkbox2">
                                    <label class="form-check-label" for="Checkbox2">Option 2</label>
                                </div>
                                <div class="form-check form-check">
                                    <input class="form-check-input" type="checkbox" id="Checkbox3">
                                    <label class="form-check-label" for="Checkbox3">Option 3</label>
                                </div>
                                <div class="form-check form-check">
                                    <input class="form-check-input" type="checkbox" id="Checkbox3" value="option3"
                                           disabled>
                                    <label class="form-check-label" for="Checkbox3">Other (disabled)</label>
                                </div>
                                <small id="emailHelp" class="form-text text-muted">We'll never share your email with
                                    anyone
                                    else.</small>
                            </div>
                        </form>
                    </div>

                    <div class="card-header">
                        <h6>Dynamic Select All</h6>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-check">
                                <input type="checkbox" id="select_all"/> <label class="form-check-label"> Select
                                All</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Apple</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Banana</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Grapes</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Papaya</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Watermelon</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Pineapple</label><br>
                                <input class="checkbox form-check-input" type="checkbox" name="check[]"> <label
                                    class="form-check-label"> Oragne</label><br>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'features/js/multiple_select/multipleselect.js' %}"></script>
    <script type="text/javascript" src="{% static 'features/js/multiple_select/dynamic_multi_select.js' %}"></script>
{% endblock %}

image_handler/templates/image_crop/image_crop.html
{% extends 'default_django_project/base.html' %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'features/css/image_crop/image_crop.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.css"
          integrity="sha512-949FvIQOibfhLTgmNws4F3DVlYz3FmCRRhJznR22hx76SKkcpZiVV5Kwo0iwK9L6BFuY+6mpdqB2+vDIGVuyHg=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.min.css"
          integrity="sha512-w+u2vZqMNUVngx+0GVZYM21Qm093kAexjueWOv9e9nIeYJb1iEfiHC7Y+VvmP/tviQyA5IR32mwN/5hTEJx6Ng=="
          crossorigin="anonymous"/>

    {#    <link rel="stylesheet" href="https://unpkg.com/jcrop/dist/jcrop.css">#}
{% endblock %}
{% block side_navigation %}
    {% include 'base_site/side_navigation.html' %}
{% endblock %}
{% block breadcrumbs %}
    {% include 'base_site/breadcrumbs.html' with data=data_breadcrumb %}
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h6>Crop Image</h6>
                    </div>
                    <div class="card-body">

                        <!-- FORM TO UPLOAD THE IMAGES -->
                        <form method="post" enctype="multipart/form-data" id="formUpload">
                            {% csrf_token %}
                            {#                                                        <div class="form-group">#}
                            {#                                                            <label>Select Image: </label>#}
                            {#                                                            #}
                            {#                                                            {{ form.x }}#}
                            {#                                                            {{ form.y }}#}
                            {#                                                            {{ form.width }}#}
                            {#                                                            {{ form.height }}#}
                            {#                                                            {{ form.file }}#}
                            {#                                                            {{ form.label }}<br>#}
                            {#                                                            {{ form.help_text }}#}
                            {#                                                            <small class="form-text text-muted">Help text written here</small>#}
                            {#                                                        </div>#}
                            <div class="form-group">
                                <label for="id_file">Example file input</label>
                                <input type="hidden" id="id_x" name="x">
                                <input type="hidden" id="id_y" name="y">
                                <input type="hidden" id="id_width" name="width">
                                <input type="hidden" id="id_height" name="height">
                                <input type="file" class="form-control-file" id="id_file" name="file">
                            </div>
                        </form>


                        <!-- MODAL TO CROP THE IMAGE -->
                        <div class="modal" id="modalCrop">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Crop the photo</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>

                                    </div>
                                    <div class="modal-body">
                                        <div class="image-container">
                                            <img src="" id="image">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="btn-group pull-left" role="group">
                                            <button type="button" class="btn btn-default js-zoom-in">
                                                <i class="fa fa-search-plus" aria-hidden="true"></i>
                                            </button>
                                            <button type="button" class="btn btn-default js-zoom-out">
                                                <i class="fa fa-search-minus" aria-hidden="true"></i>
                                            </button>
                                        </div>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind
                                        </button>
                                        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and
                                            upload
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
                        <div class="row" style="margin-top: 20px">
                            {% for photo in photos %}
                                <div class="col-sm-4 col-md-3">

                                    <img src="{{ photo.file.url }}" class="thumbnail">
                                    {#                                    <img src="{{ photo.file.url }}" width="200px" height="200px">#}
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.js"
            integrity="sha512-oqBsjjSHWqkDx4UKoU+5IUZN2nW2qDp2GFSKw9+mcFm+ZywqfBKp79nfWmGPco2wzTWuE46XpjtCjZ9tFmI12g=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cropper/1.0.1/jquery-cropper.min.js"
            integrity="sha512-V8cSoC5qfk40d43a+VhrTEPf8G9dfWlEJgvLSiq2T2BmgGRmZzB8dGe7XAABQrWj3sEfrR5xjYICTY4eJr76QQ=="
            crossorigin="anonymous"></script>

    <script type="text/javascript"
            src="{% static 'features/js/image_crop/hide_image_overlay.js' %}"></script>
    <script type="text/javascript"
            src="{% static '/features/js/image_crop/image_cropperjs.js' %}"></script>
{% endblock %}

image_handler/templates/image_drag_and_drop/image_drag_and_drop.html
{% extends 'default_django_project/base.html' %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/dropzone.min.css"
          integrity="sha512-3g+prZHHfmnvE1HBLwUnVuunaPOob7dpksI7/v6UnF/rnKGwHf/GdEq9K7iEN7qTtW+S0iivTcGpeTBqqB04wA=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'features/css/image_drag_and_drop/image_drag_and_drop.css' %}">
{% endblock %}
{% block side_navigation %}
    {% include 'base_site/side_navigation.html' %}
{% endblock %}
{% block breadcrumbs %}
    {% include 'base_site/breadcrumbs.html' with data=data_breadcrumb %}
{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="container">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h6>Drag And Drop Images</h6>
                    </div>
                    <div class="card-body">
                        <div id="dropzone">
                            <form id="dropZoneForm" class="dropzone needsclick dz-clickable" action="#" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="abc" value="i am hidden value">
                                <div class="fallback">
                                    <input name="file" type="file" multiple/>
                                </div>
                            </form>
                            <br>
                            <input type="submit" id="submit-all" value="Upload" class="custom-button"
                                   style="float: right">


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"
            integrity="sha512-9WciDs0XP20sojTJ9E7mChDXy6pcO0qHpwbEJID1YVavz2H6QBz5eLoDD8lseZOb2yGT8xDNIV7HIe1ZbuiDWg=="
            crossorigin="anonymous"></script>

    <script type="text/javascript"
            src="{% static '/features/js/image_drag_and_drop/image_drag_and_drop.js' %}"></script>
{% endblock %}

responsive_form/templates/base_site/base_css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

<link rel="stylesheet" href="{% static 'responsive_form/css/sidebar.css' %}">
<link rel="stylesheet" href="{% static 'responsive_form/css/header.css' %}">
<link rel="stylesheet" href="{% static 'responsive_form/css/breadcrumbs.css' %}">
<link rel="stylesheet" href="{% static 'responsive_form/css/base.css' %}">
<link rel="stylesheet" href="{% static 'responsive_form/css/card.css' %}">

responsive_form/templates/base_site/breadcrumbs.html
{#<nav aria-label="breadcrumb">#}
<br>
<div class="breadcrumb-div nav-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Home</a></li>
{#        <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Home</a></li>#}
        {#        <li class="breadcrumb-item active" aria-current="page">Data</li>#}
        <li class="breadcrumb-item {{ data.active }}" aria-current="page">{{ data.name }}</li>
    </ol>
</div>
{#</nav>#}

responsive_form/templates/base_site/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

responsive_form/templates/base_site/side_navigation.html
{#https://bootstrapious.com/p/bootstrap-sidebar#}

<!-- Sidebar -->
<nav id="sidebar">
    {#        <div class="sidebar-header">#}
    {#            <h3>Bootstrap Sidebar</h3>#}
    {#        </div>#}
    <ul class="ul-sidebar">
        <li class="sidebar-header">Main</li>
        <li class="sidebar-item"><a class="sidebar-link" href="{% url 'dashboard' %}"><i class="fa fa-home"
                                                                                         aria-hidden="true"></i>
            Dashboard</a>
        </li>
        <li class="sidebar-header">Elements</li>
        <li class="sidebar-item">
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link item">
                <i class="fa fa-table" aria-hidden="true"></i> Table</a>

            <ul class="sidebar-dropdown list-unstyled collapse" id="pageSubmenu">
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">Table 1</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">Table 2</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">Table 3</a>
                </li>
            </ul>
        </li>

        <li class="sidebar-item">
            <a href="#FormCRUD" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link item">
                <i class="fa fa-list" aria-hidden="true"></i> Forms</a>

            <ul class="sidebar-dropdown list-unstyled collapse" id="FormCRUD">
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'responsive_from:create_from' %}">Create</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">Update</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="#">List</a>
                </li>
            </ul>
        </li>

        <li class="sidebar-item">
            <a href="#Features" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link item">
                <i class="fa fa-magic" aria-hidden="true"></i> Features</a>

            <ul class="sidebar-dropdown list-unstyled collapse" id="Features">
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'features:multiple_select' %}">Multiple Select</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'features:multiple_divison' %}">Multiple Divison</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'image_handler:image_crop' %}">Image Crop</a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="{% url 'image_handler:image_drag_and_drop' %}">Image Drag And Drop</a>
                </li>
            </ul>
        </li>

        <li class="sidebar-header">About</li>
        <li class="sidebar-item">
            <a class="sidebar-link" href="#">Portfolio</a>
        </li>
        <li class="sidebar-item">
            <a class="sidebar-link" href="#">Contact</a>
        </li>
    </ul>

</nav>
{% block extrajs %}
{% endblock %}